// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {screenshot} from '../models';
import {main} from '../models';
import {windows} from '../models';

export function CaptureDisplay(arg1:number):Promise<screenshot.CaptureResult>;

export function CaptureFullscreen():Promise<screenshot.CaptureResult>;

export function CaptureRegion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<screenshot.CaptureResult>;

export function CaptureWindow(arg1:number):Promise<screenshot.CaptureResult>;

export function GetDisplayBounds(arg1:number):Promise<main.DisplayBounds>;

export function GetDisplayCount():Promise<number>;

export function GetHotkeyConfig():Promise<main.HotkeyConfig>;

export function GetWindowInfo(arg1:number):Promise<windows.WindowInfo>;

export function GetWindowList():Promise<Array<windows.WindowInfo>>;

export function MinimizeToTray():Promise<void>;

export function QuickSave(arg1:string,arg2:string):Promise<main.SaveImageResult>;

export function SaveImage(arg1:string,arg2:string):Promise<main.SaveImageResult>;

export function ShowWindow():Promise<void>;
