// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureDisplay(arg1) {
  return window['go']['main']['App']['CaptureDisplay'](arg1);
}

export function CaptureFullscreen() {
  return window['go']['main']['App']['CaptureFullscreen']();
}

export function CaptureRegion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureRegion'](arg1, arg2, arg3, arg4);
}

export function CaptureWindow(arg1) {
  return window['go']['main']['App']['CaptureWindow'](arg1);
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function FinishRegionCapture() {
  return window['go']['main']['App']['FinishRegionCapture']();
}

export function GetActiveDisplayIndex() {
  return window['go']['main']['App']['GetActiveDisplayIndex']();
}

export function GetBackgroundImages() {
  return window['go']['main']['App']['GetBackgroundImages']();
}

export function GetClipboardImage() {
  return window['go']['main']['App']['GetClipboardImage']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDisplayBounds(arg1) {
  return window['go']['main']['App']['GetDisplayBounds'](arg1);
}

export function GetDisplayCount() {
  return window['go']['main']['App']['GetDisplayCount']();
}

export function GetHotkeyConfig() {
  return window['go']['main']['App']['GetHotkeyConfig']();
}

export function GetSkippedVersion() {
  return window['go']['main']['App']['GetSkippedVersion']();
}

export function GetVirtualScreenBounds() {
  return window['go']['main']['App']['GetVirtualScreenBounds']();
}

export function GetWindowInfo(arg1) {
  return window['go']['main']['App']['GetWindowInfo'](arg1);
}

export function GetWindowList() {
  return window['go']['main']['App']['GetWindowList']();
}

export function GetWindowListWithThumbnails() {
  return window['go']['main']['App']['GetWindowListWithThumbnails']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PrepareRegionCapture() {
  return window['go']['main']['App']['PrepareRegionCapture']();
}

export function QuickSave(arg1, arg2) {
  return window['go']['main']['App']['QuickSave'](arg1, arg2);
}

export function SaveBackgroundImages(arg1) {
  return window['go']['main']['App']['SaveBackgroundImages'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetSkippedVersion(arg1) {
  return window['go']['main']['App']['SetSkippedVersion'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UpdateWindowSize(arg1, arg2) {
  return window['go']['main']['App']['UpdateWindowSize'](arg1, arg2);
}
