// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureDisplay(arg1) {
  return window['go']['main']['App']['CaptureDisplay'](arg1);
}

export function CaptureFullscreen() {
  return window['go']['main']['App']['CaptureFullscreen']();
}

export function CaptureRegion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureRegion'](arg1, arg2, arg3, arg4);
}

export function CaptureWindow(arg1) {
  return window['go']['main']['App']['CaptureWindow'](arg1);
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function ClearGDriveCredentials() {
  return window['go']['main']['App']['ClearGDriveCredentials']();
}

export function ClearR2Credentials() {
  return window['go']['main']['App']['ClearR2Credentials']();
}

export function DeleteScreenshot(arg1) {
  return window['go']['main']['App']['DeleteScreenshot'](arg1);
}

export function DisconnectGDrive() {
  return window['go']['main']['App']['DisconnectGDrive']();
}

export function FinishRegionCapture() {
  return window['go']['main']['App']['FinishRegionCapture']();
}

export function GetActiveDisplayIndex() {
  return window['go']['main']['App']['GetActiveDisplayIndex']();
}

export function GetBackgroundImages() {
  return window['go']['main']['App']['GetBackgroundImages']();
}

export function GetClipboardImage() {
  return window['go']['main']['App']['GetClipboardImage']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDisplayBounds(arg1) {
  return window['go']['main']['App']['GetDisplayBounds'](arg1);
}

export function GetDisplayCount() {
  return window['go']['main']['App']['GetDisplayCount']();
}

export function GetEditorConfig() {
  return window['go']['main']['App']['GetEditorConfig']();
}

export function GetGDriveConfig() {
  return window['go']['main']['App']['GetGDriveConfig']();
}

export function GetGDriveStatus() {
  return window['go']['main']['App']['GetGDriveStatus']();
}

export function GetHotkeyConfig() {
  return window['go']['main']['App']['GetHotkeyConfig']();
}

export function GetLibraryImages() {
  return window['go']['main']['App']['GetLibraryImages']();
}

export function GetR2Config() {
  return window['go']['main']['App']['GetR2Config']();
}

export function GetSkippedVersion() {
  return window['go']['main']['App']['GetSkippedVersion']();
}

export function GetVirtualScreenBounds() {
  return window['go']['main']['App']['GetVirtualScreenBounds']();
}

export function GetWindowInfo(arg1) {
  return window['go']['main']['App']['GetWindowInfo'](arg1);
}

export function GetWindowList() {
  return window['go']['main']['App']['GetWindowList']();
}

export function GetWindowListWithThumbnails() {
  return window['go']['main']['App']['GetWindowListWithThumbnails']();
}

export function HasGDriveCredentials() {
  return window['go']['main']['App']['HasGDriveCredentials']();
}

export function IsGDriveConnected() {
  return window['go']['main']['App']['IsGDriveConnected']();
}

export function IsR2Configured() {
  return window['go']['main']['App']['IsR2Configured']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PrepareRegionCapture() {
  return window['go']['main']['App']['PrepareRegionCapture']();
}

export function QuickSave(arg1, arg2) {
  return window['go']['main']['App']['QuickSave'](arg1, arg2);
}

export function SaveBackgroundImages(arg1) {
  return window['go']['main']['App']['SaveBackgroundImages'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveEditorConfig(arg1) {
  return window['go']['main']['App']['SaveEditorConfig'](arg1);
}

export function SaveGDriveConfig(arg1) {
  return window['go']['main']['App']['SaveGDriveConfig'](arg1);
}

export function SaveGDriveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveGDriveCredentials'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveR2Config(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveR2Config'](arg1, arg2, arg3, arg4);
}

export function SaveR2Credentials(arg1, arg2) {
  return window['go']['main']['App']['SaveR2Credentials'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetSkippedVersion(arg1) {
  return window['go']['main']['App']['SetSkippedVersion'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartGDriveAuth() {
  return window['go']['main']['App']['StartGDriveAuth']();
}

export function TestR2Connection() {
  return window['go']['main']['App']['TestR2Connection']();
}

export function UpdateWindowSize(arg1, arg2) {
  return window['go']['main']['App']['UpdateWindowSize'](arg1, arg2);
}

export function UploadToGDrive(arg1, arg2) {
  return window['go']['main']['App']['UploadToGDrive'](arg1, arg2);
}

export function UploadToR2(arg1, arg2) {
  return window['go']['main']['App']['UploadToR2'](arg1, arg2);
}
