// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {screenshot} from '../models';
import {updater} from '../models';
import {config} from '../models';
import {main} from '../models';
import {windows} from '../models';

export function CaptureDisplay(arg1:number):Promise<screenshot.CaptureResult>;

export function CaptureFullscreen():Promise<screenshot.CaptureResult>;

export function CaptureRegion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<screenshot.CaptureResult>;

export function CaptureWindow(arg1:number):Promise<screenshot.CaptureResult>;

export function CheckForUpdate(arg1:string):Promise<updater.UpdateInfo>;

export function FinishRegionCapture():Promise<void>;

export function GetActiveDisplayIndex():Promise<number>;

export function GetBackgroundImages():Promise<Array<string>>;

export function GetClipboardImage():Promise<screenshot.CaptureResult>;

export function GetConfig():Promise<config.Config>;

export function GetDisplayBounds(arg1:number):Promise<main.DisplayBounds>;

export function GetDisplayCount():Promise<number>;

export function GetHotkeyConfig():Promise<main.HotkeyConfig>;

export function GetSkippedVersion():Promise<string>;

export function GetVirtualScreenBounds():Promise<main.VirtualScreenBounds>;

export function GetWindowInfo(arg1:number):Promise<windows.WindowInfo>;

export function GetWindowList():Promise<Array<windows.WindowInfo>>;

export function GetWindowListWithThumbnails():Promise<Array<windows.WindowInfoWithThumbnail>>;

export function MinimizeToTray():Promise<void>;

export function OpenImage():Promise<screenshot.CaptureResult>;

export function OpenURL(arg1:string):Promise<void>;

export function PrepareRegionCapture():Promise<main.RegionCaptureData>;

export function QuickSave(arg1:string,arg2:string):Promise<main.SaveImageResult>;

export function SaveBackgroundImages(arg1:Array<string>):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveImage(arg1:string,arg2:string):Promise<main.SaveImageResult>;

export function SelectFolder():Promise<string>;

export function SetSkippedVersion(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateWindowSize(arg1:number,arg2:number):Promise<void>;
