// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureDisplay(arg1) {
  return window['go']['main']['App']['CaptureDisplay'](arg1);
}

export function CaptureFullscreen() {
  return window['go']['main']['App']['CaptureFullscreen']();
}

export function CaptureRegion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureRegion'](arg1, arg2, arg3, arg4);
}

export function CaptureWindow(arg1) {
  return window['go']['main']['App']['CaptureWindow'](arg1);
}

export function GetDisplayBounds(arg1) {
  return window['go']['main']['App']['GetDisplayBounds'](arg1);
}

export function GetDisplayCount() {
  return window['go']['main']['App']['GetDisplayCount']();
}

export function GetHotkeyConfig() {
  return window['go']['main']['App']['GetHotkeyConfig']();
}

export function GetWindowInfo(arg1) {
  return window['go']['main']['App']['GetWindowInfo'](arg1);
}

export function GetWindowList() {
  return window['go']['main']['App']['GetWindowList']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function QuickSave(arg1, arg2) {
  return window['go']['main']['App']['QuickSave'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
